### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [Hygens/mt7610u_ubuntu_1610#3]
On `make` there is an error that makes the compilation fail:

    ./include/linux/string.h:340:4: error: call to ‘__read_overflow2’ declared with attribute error: detected read beyond size of object passed as 2nd parameter
        __read_overflow2();
        ^~~~~~~~~~~~~~~~~~

`gcc --version`:

    gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0
    Copyright (C) 2017 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`uname -a`

    Linux xiaolong-hp-pavilion 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

If any more info is required simply tell me and I'll try.

**Comment by Hygens** [comment]
Not possible compile on that kernel. Verify the prerequisites on https://github.com/Hygens/mt7610u_ubuntu_1610/wiki, only kernels:
Linux Mint 18(Kernel 4.4.0-43-generic) or 
Ubuntu 16.10(Kernel 4.8.0-41-generic) 

The driver is no more compatible with the more recent versions on kernels 4.15* and forward.
Search on GitHUb if some person have get that driver work on that version or if you think that you can help here, I'm gratefull.
If you googling you verify that TPLInk have observed the incompatibility for that dongle on recente kernels and no more have supported that.
I'm not using more that driver because I'm using Ubuntu 18.04 with kernel 4.15.0-34-generic.

**Comment by Hygens** [comment]
For that informations. I closing that issue.
